style: landing page
lukso-network/network-deposit-launchpad pull request #1
Opened 2022-12-01 15:27 UTC by dzbo

https://app.clickup.com/t/33a6bb7

### Desktop
![CleanShot 2022-12-01 at 15 53 44@2x](https://user-images.githubusercontent.com/1100879/205084816-2bcc04bd-4746-4bea-9a6b-4a1c00fc5085.png)

### Mobile
<img src="https://user-images.githubusercontent.com/1100879/205086888-7c866edd-deb6-444b-a802-9a74caa7a445.png" width="400" />

2022-12-02 10:10 UTC, frozeman commented
For anyone watching this, the text is not changed yet.. thats why it says ethereum CC community :P

2022-12-02 10:38 UTC, dzbo commented
> For anyone watching this, the text is not changed yet.. thats why it says ethereum CC community :P

For now it's just about visuals, I will work as next step on texts as planned initially. Here is task for this https://app.clickup.com/t/334atdu

2022-12-02 15:29 UTC, dzbo commented on src/components/WorkflowPage/WorkflowProgressBar.tsx
> +              className={workflow === step ? 'active' : ''}
We need this to track what is current active step. It can't be targeted because styled components apply some random class only.

2022-12-02 15:32 UTC, dzbo commented on src/App.tsx
> +              <CustomFooter />
We add our own footer component since it has in addition our own links.

2022-12-06 10:15 UTC, CallumGrindle commented on src/styles/luksoTheme/functions/number.scss
> +}
Wow makes me appreciate `parseInt` in JS a lot more 😄 Maybe this could go in a utils repo rater than the core theme functions?

2022-12-06 10:36 UTC, CallumGrindle approved these changes
LGTM

2022-12-06 10:55 UTC, dzbo commented
> LGTM

Thanks for review, it's still WIP tho. Sorry if that wasn't clear, I've should keep it as draft from the start. If this is fine I will ass for re-review once whole restyle is completed :)

2022-12-06 11:39 UTC, CallumGrindle commented
> > LGTM
> 
> Thanks for review, it's still WIP tho. Sorry if that wasn't clear, I've should keep it as draft from the start. If this is fine I will ass for re-review once whole restyle is completed :)

Ah okay no problem just let me know :)

2022-12-13 10:29 UTC, dzbo commented
@CallumGrindle ready for re-review ;)

2022-12-13 10:29 UTC, dzbo commented on src/components/Alert.tsx
> +const AlertBox = styled(Box)``;
This just apply new class in the DOM for this elements, otherwise it was not targetable with CSS

2022-12-13 10:30 UTC, dzbo commented on src/components/SelectionBox.tsx
> +      className={isActive ? 'active' : ''}
Need to apply `active` class for styling active element. Styled components apply random class that can't be targeted with CSS.

2022-12-14 11:32 UTC, richtera approved these changes
LGTM

2022-12-14 15:47 UTC, Hugoo commented on public/index.html
>      <meta name="fortmatic-site-verification" content="QOrxrue6v0Rw4eMI" />
i think this will need to be replaced - maybe we can remove it? Or in next pr.

2022-12-14 15:47 UTC, Hugoo commented on src/styles/luksoTheme/font.scss
> +  src: url('./fonts/PT Mono Regular.woff2') format('woff2');
would it be better to remove whitespaces? and put - or _ instead?

2022-12-14 16:20 UTC, dzbo commented on public/index.html
>      <meta name="fortmatic-site-verification" content="QOrxrue6v0Rw4eMI" />
For sure, there is "improvements" ticket already. I will include in the list.

2022-12-14 16:21 UTC, dzbo commented on src/styles/luksoTheme/font.scss
> +  src: url('./fonts/PT Mono Regular.woff2') format('woff2');
Sounds good 👍

2022-12-15 12:46 UTC, richtera requested changes

2022-12-15 12:46 UTC, richtera commented on src/pages/ConnectWallet/index.tsx
> +            // disabled={
Is this commented out on the uprise or show ups it be deleted?

2022-12-15 12:46 UTC, richtera commented on src/pages/UploadValidator/index.tsx
> +            // disabled={!isFileAccepted}
Same; delete it?

2022-12-19 15:16 UTC, richtera approved these changes
The code looks good. The many styles with class*= might be slow but look correct

2023-01-04 09:51 UTC, richtera commented on src/components/WorkflowPage/WorkflowProgressBar.tsx
> +              className={workflow === step ? 'active' : ''}
You should be able to import the actual class from the CSS file. The babel style modules should export an item called "active" containing the actual class name.

2023-01-04 13:02 UTC, dzbo commented on src/components/WorkflowPage/WorkflowProgressBar.tsx
> +              className={workflow === step ? 'active' : ''}
I'm not sure if I follow that, can you point me to some example?

2023-01-04 18:35 UTC, richtera commented on src/components/WorkflowPage/WorkflowProgressBar.tsx
> +              className={workflow === step ? 'active' : ''}
I am thinking something like this:
```js

const BarLinkText = styled(Heading)`
  :not(.no-padding) {
    padding: 0 12px;
    white-space: nowrap;
  }
  display: flex;
  justify-content: center;
  flex-direction: column;
  font-weight: ${(p: { active?: boolean }) => (p.active ? 'bold' : 300)};
`;
```
Normally this is imported from css modules, but it looks like this app uses only styled components.
So for example if css modules is on and the css contains.
```css
.active {
   ...
}
```
then the import
```js
import { active } from "./style.css"
// active would resolve to the actual module css name (i.e. a scoped active_hash for example)
```

2023-01-05 13:31 UTC, frozeman commented
Lets not merge this yet. ill create a fork from this branch from this one for the text changes

2023-01-20 13:56 UTC, closed without merging